DeliveryService/Models/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DeliveryService.Models.ViewModels
{
    public class LoginViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Contact { get; set; }
    }
}

DeliveryService/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DeliveryService.Models.Services;
using DeliveryService.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DeliveryService.Controllers
{
    public class AdminController : Controller
    {
        private AdminService _adminService;

        public AdminController(AdminService adminService)
        {
            _adminService = adminService;
        }

        public IActionResult Index()
        {
            var countCustomer = _adminService.CountCustomer();
            var countLocation = _adminService.CountLocation();
            var countCompany = _adminService.CountCompany();

            ViewData["company"] = countCompany;
            ViewData["location"] = countLocation;
            ViewData["customer"] = countCustomer;

            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(AdminViewModel model)
        {

            var exist = _adminService.Login(model);

            if (exist)
            {
                return RedirectToAction("Index", "AdminController");
            }
            else
            {
                ViewBag.Message = "Invalid Credentials Entered";
                return View();
            }
        }


    }
}

DeliveryService/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DeliveryService.Models.Services;
using DeliveryService.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DeliveryService.Controllers
{
    public class CompanyController : Controller
    {
        // GET: Company

        private CompanyService _companyService;

        public CompanyController(CompanyService companyService)
        {
            _companyService = companyService;
        }
        public ActionResult Index()
        {
            var model = _companyService.GetCompanies();
            return View(model);
        }

        // GET: Company/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var model = _companyService.GetCompanyDetails(id);
                return View(model);
            }
            catch (Exception)
            {

                return RedirectToAction(nameof(Index));
            }
        }




        // GET: Company/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Company/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CompanyViewModel model)
        {
            try
            {
                // TODO: Add insert logic here
                var result = _companyService.AddCompany(model);

                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
                throw new Exception();

                
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "oops something went wrong");
                return View();
            }
        }

        // GET: Company/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var model = _companyService.GetCompanyDetails(id);
                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Index));
            }
           
        }

        // POST: Company/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CompanyViewModel model)
        {
            try
            {
                // TODO: Add update logic here
                var result = _companyService.UpdateCompany(model);

                if (result)
                {
                return RedirectToAction(nameof(Index));

                }
                throw new Exception();

            }
            catch
            {
                ModelState.AddModelError(string.Empty, "OOps something went wrong");
                return View();
            }
        }

        // GET: Company/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var model = _companyService.GetCompanyDetails(id);
                return View(model);
                
            }
            catch (Exception)
            {

                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Company/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, CompanyViewModel model)
        {
            try
            {
                
                // TODO: Add delete logic here
                bool result = _companyService.RemoveCompany(id);
                if (result)
                {
                return RedirectToAction(nameof(Index));

                }
                throw new Exception();

            }
            catch
            {
                ModelState.AddModelError(string.Empty, "OOps something went wrong");
                return View();
            }
        }
    }
}

DeliveryService/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DeliveryService.Models;
using DeliveryService.Models.Services;
using DeliveryService.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DeliveryService.Controllers
{
    public class PagesController : Controller
    {
         
        private PagesService _pagesService;
        private CustomerOrderService _customerOrderService;
        private CustomerService _customerService;
        public PagesController(PagesService pagesService, CustomerOrderService customerOrderService, CustomerService customerService)
        {
            _pagesService = pagesService;
            _customerOrderService = customerOrderService;
            _customerService = customerService;
        }
        public IActionResult Index()
        {
            var locations = _pagesService.ListLocation();

            ViewData["locations"] = locations;

            var prices = _pagesService.ListPrices();
            ViewData["Prices"] = prices;

            var model = _pagesService.create();
            return View(model);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Services()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult Request()
        {
            var model = _pagesService.create();
            return View(model);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(CustomerViewModel model)
         {
            
                var exist = _customerService.Login(model);

                if ( exist)
                {
                    return RedirectToAction("Request", "PagesController");
                }
                else
                {
                    ViewBag.Message = "Invalid Credentials Entered";
                    return View();
                }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DeliveryService/Controllers/PriceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DeliveryService.Models.Services;
using DeliveryService.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DeliveryService.Controllers
{
    public class PriceController : Controller
    {
        // GET: Price
        private PriceService _priceService;

        public PriceController(PriceService priceService)
        {
            _priceService = priceService;
        }
        public ActionResult Index()
        {
            var model = _priceService.GetPrices();
            return View(model);
            
        }

        // GET: Price/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var model = _priceService.GetPriceDetails(id);
                return View(model);
            }
            catch (Exception)
            {

                return RedirectToAction(nameof(Index));
            }
        }

        // GET: Price/Create
        public ActionResult Create()
        {
            var model = _priceService.CreatePrice();
            return View(model);
        }

        // POST: Price/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PriceViewModel model)
        {
            try
            {
                // TODO: Add insert logic here
                var result = _priceService.AddPrice(model);

                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
                throw new Exception();


            }
            catch
            {
                ModelState.AddModelError(string.Empty, "oops something went wrong");
                return View();
            }
        }

        // GET: Price/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var model = _priceService.GetPriceDetails(id);
                return View(model);
            }
            catch
            {

                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Price/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PriceViewModel model)
        {
            try
            {
                bool result = _priceService.UpdatePrice(model);

                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
                throw new Exception();
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Ooops! Something went wrong!");
                return View();
            }
        }

        // GET: Price/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var model = _priceService.GetPriceDetails(id);
                return View(model);
            }
            catch
            {

                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Price/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, PriceViewModel model)
        {
            try
            {
                bool result = _priceService.RemovePrice(id);

                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
                throw new Exception();
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Ooops! Something went wrong!");
                return View();
            }
        }
    }
}

DeliveryService/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin-@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">

    <link rel="stylesheet" href="~/dashboard/vendors/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/dashboard/vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/dashboard/vendors/themify-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/dashboard/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/dashboard/vendors/selectFX/css/cs-skin-elastic.css">
    <link rel="stylesheet" href="~/dashboard/vendors/jqvmap/dist/jqvmap.min.css">


    <link rel="stylesheet" href="~/dashboard/assets/css/style.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
</head>
<body>
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">

            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="./">Admin</a>
            </div>

            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active" style="font-size:20px; color:white">
                        <a asp-controller="Admin" asp-action="Index"><i class="menu-icon fa fa-dashboard"></i>Dashboard</a>
                    </li>
                    <li class="active" style="font-size:20px; color:white">
                        <a asp-controller="Company" asp-action="Index"><i class="menu-icon fa fa-desktop"></i> Companies</a>
                    </li>
                    <li class="active" style="font-size:20px; color:white">
                        <a asp-controller="Customer" asp-action="Index"><i class="menu-icon fa fa-users"></i> Customers</a>
                    </li>
                    <li class="active" style="font-size:20px; color:white">
                        <a asp-controller="Location" asp-action="Index"><i class="menu-icon fa fa-map-marker"></i>Locations</a>
                    </li>
                    <li class="active" style="font-size:20px; color:white">
                        <a asp-controller="Price" asp-action="Index"><i class="menu-icon fa fa-money"></i>Pricing</a>
                    </li>
                    <li class="active" style="font-size:20px; color:white">
                        <a asp-controller="Customer" asp-action="Index"><i class="menu-icon fa fa-shopping-bag"></i>Customer Order</a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside><!-- /#left-panel -->
    <!-- Left Panel -->
    <!-- Right Panel -->

    <div id="right-panel" class="right-panel">

        <!-- Header-->
        <header id="header" class="header">

            <div class="header-menu">

                <div class="col-sm-7">
                    <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                    <div class="header-left">
                        <button class="search-trigger"><i class="fa fa-search"></i></button>
                        <div class="form-inline">
                            <form class="search-form">
                                <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                                <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                            </form>
                        </div>

                        <div class="dropdown for-notification">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-bell"></i>
                                <span class="count bg-danger">5</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="notification">
                                <p class="red">You have 3 Notification</p>
                                <a class="dropdown-item media bg-flat-color-1" href="#">
                                    <i class="fa fa-check"></i>
                                    <p>Server #1 overloaded.</p>
                                </a>
                                <a class="dropdown-item media bg-flat-color-4" href="#">
                                    <i class="fa fa-info"></i>
                                    <p>Server #2 overloaded.</p>
                                </a>
                                <a class="dropdown-item media bg-flat-color-5" href="#">
                                    <i class="fa fa-warning"></i>
                                    <p>Server #3 overloaded.</p>
                                </a>
                            </div>
                        </div>

                        <div class="dropdown for-message">
                            <button class="btn btn-secondary dropdown-toggle" type="button"
                                    id="message"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="ti-email"></i>
                                <span class="count bg-primary">9</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="message">
                                <p class="red">You have 4 Mails</p>
                                <a class="dropdown-item media bg-flat-color-1" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="~/dashboard/images/avatar/1.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Jonathan Smith</span>
                                        <span class="time float-right">Just now</span>
                                        <p>Hello, this is an example msg</p>
                                    </span>
                                </a>
                                <a class="dropdown-item media bg-flat-color-4" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="~/dashboard/images/avatar/2.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Jack Sanders</span>
                                        <span class="time float-right">5 minutes ago</span>
                                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                                    </span>
                                </a>
                                <a class="dropdown-item media bg-flat-color-5" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="~/dashboard/images/avatar/3.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Cheryl Wheeler</span>
                                        <span class="time float-right">10 minutes ago</span>
                                        <p>Hello, this is an example msg</p>
                                    </span>
                                </a>
                                <a class="dropdown-item media bg-flat-color-3" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="~/dashboard/images/avatar/4.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Rachel Santos</span>
                                        <span class="time float-right">15 minutes ago</span>
                                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-5">
                    <div class="user-area dropdown float-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="user-avatar rounded-circle" src="~/dashboard/images/admin.jpg" alt="User Avatar">
                        </a>

                        <div class="user-menu dropdown-menu">
                            <a class="nav-link" href="#"><i class="fa fa-user"></i> My Profile</a>

                            <a class="nav-link" href="#"><i class="fa fa-user"></i> Notifications <span class="count">13</span></a>

                            <a class="nav-link" href="#"><i class="fa fa-cog"></i> Settings</a>

                            <a class="nav-link" href="#"><i class="fa fa-power-off"></i> Logout</a>
                        </div>
                    </div>

                    <div class="language-select dropdown" id="language-select">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="language" aria-haspopup="true" aria-expanded="true">
                            <i class="flag-icon flag-icon-us"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="language">
                            <div class="dropdown-item">
                                <span class="flag-icon flag-icon-fr"></span>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-es"></i>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-us"></i>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-it"></i>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </header><!-- /header -->
        <!-- Header-->
        <div class="breadcrumbs">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Dashboard</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li class="active">Dashboard</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="container">
            @RenderBody()

            </div>
        </div>

        <script src="~/dashboard/vendors/jquery/dist/jquery.min.js"></script>
        <script src="~/dashboard/vendors/popper.js/dist/umd/popper.min.js"></script>
        <script src="~/dashboard/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/dashboard/assets/js/main.js"></script>


        <script src="~/dashboard/vendors/chart.js/dist/Chart.bundle.min.js"></script>
        <script src="~/dashboard/assets/js/dashboard.js"></script>
        <script src="~/dashboard/assets/js/widgets.js"></script>
        <script src="~/dashboard/vendors/jqvmap/dist/jquery.vmap.min.js"></script>
        <script src="~/dashboard/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
        <script src="~/dashboard/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
        <script>
            (function ($) {
                "use strict";

                jQuery('#vmap').vectorMap({
                    map: 'world_en',
                    backgroundColor: null,
                    color: '#ffffff',
                    hoverOpacity: 0.7,
                    selectedColor: '#1de9b6',
                    enableZoom: true,
                    showTooltip: true,
                    values: sample_data,
                    scaleColors: ['#1de9b6', '#03a9f5'],
                    normalizeFunction: 'polynomial'
                });
            })(jQuery);
        </script>
        @RenderSection("scripts", required: false)
</body>
</html>

DeliveryService/Views/Shared/_Login.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="icon" type="image/png" href="~/Login/images/icons/favicon.ico" />
  
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/bootstrap/css/bootstrap.min.css">
    
    <link rel="stylesheet" type="text/css" href="~/Login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    
    <link rel="stylesheet" type="text/css" href="~/Login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
   
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/animate/animate.css">
    
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/css-hamburgers/hamburgers.min.css">
   
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/animsition/css/animsition.min.css">
    
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/select2/select2.min.css">
    
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/daterangepicker/daterangepicker.css">
    
    <link rel="stylesheet" type="text/css" href="~/Login//css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Login/css/main.css">
    
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <script src="~/Login/vendor/jquery/jquery-3.2.1.min.js"></script>
    <script src="~/Login/vendor/animsition/js/animsition.min.js"></script>
    <script src="~/Login/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Login/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Login/vendor/select2/select2.min.js"></script>
    <script src="~/Login/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/Login/vendor/daterangepicker/daterangepicker.js"></script>
    <script src="~/Login/vendor/countdowntime/countdowntime.js"></script>
    <script src="~/Login/js/main.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>